# This workflow will build the engine-ia and push a corresponding Docker image to Dockerhub
name: Push docker image to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"
  pull_request:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=branch::${GITHUB_REF#refs/*/}
          echo ::set-output name=tag::${GITHUB_SHA::8}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest engine-ia JDK 17
#        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./jdk17
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }},
