# This workflow will build the engine-ia and push a corresponding Docker image to Dockerhub
name: Push docker image to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push latest engine-ia JDK 8
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./jdk8
          platforms: linux/amd64,linux/arm64
          push: true
          tags: opentosca/engine-ia:latest-jdk8
      - name: Build and push latest engine-ia JDK 17
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./jdk17
          platforms: linux/amd64,linux/arm64
          push: true
          tags: opentosca/engine-ia:latest-jdk17
